apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: web-show-pod-kill
spec:
  schedule: '@every 10s'
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    duration: 30s
    selector:
      namespaces:
      - default
      labelSelectors:
        app: web-show
