apiVersion: v1
kind: Service
metadata:
  name: web-show
  labels:
    app: web-show
spec:
  selector:
    app: web-show
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-show
  labels:
    app: web-show
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-show
  template:
    metadata:
      labels:
        app: web-show
    spec:
      containers:
        - name: web-show
          image: ghcr.io/chaos-mesh/web-show
          imagePullPolicy: Always
          command:
            - /usr/local/bin/web-show
            - --target-ip=8.8.8.8
          env:
            - name: TARGET_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: web-port
              containerPort: 8081
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
